# Generated by Django 6.0.3 on 2026-05-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_1h_left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='notification_due_left',
            field=models.BooleanField(default=False),
        ),
    ]
