# Generated by Django 5.2.14 on 2026-05-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisecatalog',
            name='technique',
            field=models.TextField(blank=True, help_text='Техника Выполнения упражения ', null=True),
        ),
    ]
