# Generated by Django 6.0.3 on 2026-05-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_exercisecatalog_technique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecatalog',
            name='technique',
            field=models.TextField(blank=True, help_text='Техника выполнения упражнения', null=True),
        ),
    ]
